{
  "comments": [
    {
      "key": {
        "uuid": "792cf5df_e78e56a1",
        "filename": "csit/libraries/OpenStackOperations.robot",
        "patchSetId": 3
      },
      "lineNbr": 1105,
      "author": {
        "id": 7779
      },
      "writtenOn": "2019-02-26T12:05:10Z",
      "side": 1,
      "message": "does it return FAIL in local testing? The documentation does not mention that code",
      "revId": "40e21412fe20334fbcb8d95ef5222295bb96b278",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "f69e417b_beed5fa7",
        "filename": "csit/libraries/OpenStackOperations.robot",
        "patchSetId": 3
      },
      "lineNbr": 1105,
      "author": {
        "id": 8310
      },
      "writtenOn": "2019-02-27T14:08:34Z",
      "side": 1,
      "message": "BuiltIn.Run Keyword And Ignore Error will return status, it is \"PASS\" or \"FAIL\".\n\ncsit/suites/netvirt/vpnservice/vpn_basic.robot L267 has an example:\n\nDelete Unknown L3VPN\n    [Documentation]    Verification of a failure response with deletion of an unknown L3VPN\n    ${status}    ${message} \u003d    BuiltIn.Run Keyword And Ignore Error    VpnOperations.VPN Delete L3VPN    vpnid\u003d${INVALID_VPN_INSTANCE_ID}\n    BuiltIn.Should Contain    ${status}    FAIL",
      "parentUuid": "792cf5df_e78e56a1",
      "revId": "40e21412fe20334fbcb8d95ef5222295bb96b278",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    }
  ]
}